import React from 'react';
import {reconcileChildSupport,supportQuote,changeCustody,paySupportArrears,parentsTogether,divorceOrderFor} from './childSupport.js';
import {funds} from './futurePlanning.js';
import {formatMoney} from './money.js';
import {PersonPortrait} from './RelationshipPortrait.jsx';
export default function ChildSupportScreen({game,setGame,onOpenPlanning}){
 const g=reconcileChildSupport(game),orders=g.childSupportOrders||[],divorces=(g.divorceObligations||[]).filter(o=>o.childIds?.length);const hasRecords=orders.length||divorces.length;
 return <div className="development-screen"><h2>Support when parents are apart</h2><p>Child support applies when you have a child with someone you are no longer dating or married to, or when the child’s other parent is outside your relationship. Parents who are together share household costs without a separate support payment.</p><p>Custody and income determine who pays or receives support. Yearly payments end at age 18; unpaid arrears remain owed. These are simplified game agreements.</p>{!hasRecords&&<section><h3>No child support agreements</h3><p>Agreements appear after a birth outside your relationship, a breakup or a divorce involving children.</p></section>}
 {orders.map(o=>{const child=g.children?.find(c=>c.id===o.childId),together=parentsTogether(g,o.otherParentId),divorce=divorceOrderFor(g,o.childId);return <section key={o.id}>{child&&<div className="realism-person"><PersonPortrait person={child}/><h3>{child.name} · Age {child.age}</h3></div>}<p>Other parent: {o.otherParentName} · {o.status}</p><p>{together?'Parents are together; ongoing child support is paused.':divorce?'Ongoing payments are covered by the divorce agreement below.':`Custody: ${o.custody} · Annual ${o.custody==='You'?'incoming':'outgoing'} support: ${formatMoney(supportQuote(g,o))}`}</p><p>Last paid {formatMoney(o.lastPaid||0)} · Last received {formatMoney(o.lastReceived||0)} · Arrears {formatMoney(o.arrears||0)}</p><label className="realism-control">Agree custody · $300<select value={o.custody} disabled={!g.alive||g.age<18||!child||child.age>=18||child.alive===false||together||Boolean(divorce)||funds(g)<300||o.changedYear===g.year} onChange={e=>setGame(current=>changeCustody(current,o.childId,e.target.value))}>{['You','Shared','Other parent'].map(v=><option key={v}>{v}</option>)}</select></label>{o.changedYear===g.year&&<p>Custody was updated this year. You can review it again next year.</p>}<button disabled={!g.alive||!o.arrears||funds(g)<=0} onClick={()=>setGame(current=>paySupportArrears(current,o.childId))}>Pay arrears · {formatMoney(Math.min(funds(g),o.arrears||0))}</button></section>;})}
 {divorces.map(o=>{const children=(g.children||[]).filter(c=>o.childIds.includes(c.id)&&divorceOrderFor(g,c.id)?.id===o.id&&c.alive!==false&&c.age<18);const former=(g.friends||[]).find(p=>p.id===o.formerSpouseId);const together=parentsTogether(g,o.formerSpouseId);const outgoing=together||o.custody==='You'?0:Math.round(children.length*(o.childSupportPerChild||0)*(o.custody==='Shared'?.5:1));const incoming=!together&&o.custody==='You'?Math.round((o.childSupportReceived||0)*children.length/Math.max(1,o.initialMinors||children.length)):0;return <section key={o.id}><h3>Divorce agreement · {former?.name||'Former spouse'}</h3><p>{children.map(c=>c.name).join(', ')||'All children have reached adulthood'} · {o.custody} custody</p>{together&&<p>Parents are together; ongoing child support is paused.</p>}<p>Annual outgoing support {formatMoney(outgoing)} · Annual incoming support {formatMoney(incoming)}</p><p>Family support arrears {formatMoney(o.arrears||0)}. This balance may include alimony.</p>{onOpenPlanning&&<button onClick={onOpenPlanning}>Review settlement and family support</button>}</section>;})}
 </div>;
}
