import {recordAge} from './lifeRecords.js';
import {useFeedbackNotice} from './OutcomeFeedback.jsx';
import {formatMoney} from './money.js';
import React,{useEffect,useId,useMemo,useState} from 'react';
import {ArrowDownRight,ArrowUpRight,ChartNoAxesCombined,Clock3,Coins,Newspaper,RefreshCw,TrendingDown,TrendingUp,Wallet,X,Check} from 'lucide-react';
import {createInvestmentMarket,instrumentPrice,marketInstruments,tickInvestmentMarket} from './investments.js';

const money=formatMoney;
const price=value=>value<.01?`$${Number(value||0).toPrecision(4)}`:value<10?`$${Number(value||0).toFixed(2)}`:money(value);
const classes=['Stocks','Bonds','Crypto','Memecoins'];
const marketKey={'Stocks':'stocks','Bonds':'bonds','Crypto':'crypto','Memecoins':'memecoins'};
function Sparkline({values=[],large=false}){
  const gradientId=`market-gradient-${useId().replace(/:/g,'')}`;
  const points=(values.length?values:[1,1,1]).slice(-40);const min=Math.min(...points);const max=Math.max(...points);const span=max-min||Math.max(1,max*.01);const coords=points.map((value,index)=>`${points.length===1?0:index/(points.length-1)*320},${92-(value-min)/span*76}`).join(' ');const up=points[points.length-1]>=points[0];
  return <svg className={`investment-chart ${large?'large':''} ${up?'up':'down'}`} viewBox="0 0 320 100" preserveAspectRatio="none" aria-label={`Simulated price chart, ${up?'up':'down'} over this period`}><defs><linearGradient id={gradientId} x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="currentColor" stopOpacity=".27"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><polygon points={`0,100 ${coords} 320,100`} fill={`url(#${gradientId})`}/><polyline points={coords} fill="none" stroke="currentColor" strokeWidth={large?3:2.6} strokeLinecap="round" strokeLinejoin="round"/></svg>;
}
export default function InvestmentMarketScreen({game,setGame}){
  const [section,setSection]=useState('Market');const [assetClass,setAssetClass]=useState('Stocks');const [category,setCategory]=useState('All');const [selectedId,setSelectedId]=useState('');const [orderAmount,setOrderAmount]=useState('1000');const [notice,setNotice]=useFeedbackNotice('');const [saleReceipt,setSaleReceipt]=useState(null);const [buyConfirmation,setBuyConfirmation]=useState(null);
  useEffect(()=>{if(!game.investments)setGame(g=>g.investments?g:{...g,investments:createInvestmentMarket(g.year)});},[game.investments,game.year,setGame]);
  useEffect(()=>{if(!game.investments)return;const timer=setInterval(()=>setGame(g=>g.investments?{...g,investments:tickInvestmentMarket(g.investments)}:g),7000);return()=>clearInterval(timer);},[Boolean(game.investments),setGame]);
  const market=game.investments||createInvestmentMarket(game.year);const universe=marketInstruments(market);const holdings=market.holdings||[];const liveInstruments=market[marketKey[assetClass]]||[];
  const summary=useMemo(()=>{const positions=holdings.map(position=>{const asset=universe.find(item=>item.id===position.assetId);const livePrice=asset?.price||0;return {...position,asset,livePrice,value:position.units*livePrice,unrealized:position.units*livePrice-position.costBasis};});const invested=positions.reduce((sum,item)=>sum+item.costBasis,0);const value=positions.reduce((sum,item)=>sum+item.value,0);const realized=market.realizedPnl||0;return {positions,invested,value,realized,unrealized:value-invested,total:realized+value-invested};},[holdings,universe,market.realizedPnl]);
  const filtered=liveInstruments.filter(item=>category==='All'||item.category===category);
  const selected=universe.find(asset=>asset.id===selectedId)||filtered[0]||liveInstruments[0];
  const categories=['All',...new Set(liveInstruments.map(asset=>asset.category))];
  const trade=(asset,direction,confirmed=false,amountOverride)=>{
    const live=game.investments;const current=marketInstruments(live).find(item=>item.id===asset.id);if(!current||(current.price<=0&&!(direction==='sell'&&current.rugged))){setNotice('Trading is halted. This position has no current market value.');return;}
    const fee=2;let next={...live};let cashDelta=0;let transaction;let realized=0;
    if(direction==='buy'){
      const amount=Math.floor(Number(amountOverride??orderAmount));if(!amount||amount<10){setNotice('Enter at least $10 for a market order.');return;}
      if(amount+fee>game.money+(game.bankBalance||0)){setNotice(`Not enough available funds. You need ${money(amount+fee)}.`);return;}
      if(!confirmed){setBuyConfirmation({assetId:asset.id,amount});return;}
      const units=Number((amount/current.price).toFixed(8));const previous=(live.holdings||[]).find(item=>item.assetId===asset.id);const oldUnits=previous?.units||0;const oldBasis=previous?.costBasis||0;const holdingsNext=previous?(live.holdings||[]).map(item=>item.assetId===asset.id?{...item,units:oldUnits+units,costBasis:oldBasis+amount+fee,averageCost:(oldBasis+amount+fee)/(oldUnits+units),lastOrderYear:game.year}:item):[...(live.holdings||[]),{assetId:asset.id,assetClass:asset.assetClass,units,costBasis:amount+fee,averageCost:(amount+fee)/units,openedYear:game.year,lastOrderYear:game.year}];
      next={...next,holdings:holdingsNext};cashDelta=-(amount+fee);transaction={id:`trade-${Date.now()}`,type:'BUY',assetId:asset.id,assetClass:asset.assetClass,symbol:asset.symbol,label:`Bought ${units.toLocaleString(undefined,{maximumFractionDigits:6})} ${asset.symbol}`,units,price:current.price,amount:-(amount+fee),fee,year:game.year,age:game.age};
    }else{
      const position=(live.holdings||[]).find(item=>item.assetId===asset.id);if(!position){setNotice('You do not hold this investment.');return;}const units=position.units;const gross=units*current.price;const saleFee=current.rugged?0:fee;const proceeds=Math.max(0,gross-saleFee);realized=proceeds-position.costBasis;next={...next,holdings:(live.holdings||[]).filter(item=>item.assetId!==asset.id),realizedPnl:(live.realizedPnl||0)+realized};cashDelta=proceeds;transaction={id:`trade-${Date.now()}`,type:current.rugged?'WRITE_OFF':'SELL',assetId:asset.id,assetClass:asset.assetClass,symbol:asset.symbol,label:current.rugged?`Wrote off worthless ${asset.symbol} position`:`Sold ${units.toLocaleString(undefined,{maximumFractionDigits:6})} ${asset.symbol}`,units,price:current.price,amount:proceeds,fee:saleFee,realizedPnl:realized,year:game.year,age:game.age};
      setSaleReceipt({name:asset.name,symbol:asset.symbol,units,price:current.price,gross,fee:saleFee,proceeds,realized,rugged:Boolean(current.rugged)});
    }
    setGame(g=>{const total=(Number(g.money)||0)+(Number(g.bankBalance)||0)+cashDelta;if(total<0){setNotice('This trade would exceed your available funds.');return g;}let moneyOnHand=Number(g.money)||0,bank=Number(g.bankBalance)||0;if(cashDelta<0){const debit=-cashDelta;const fromCash=Math.min(Math.max(0,moneyOnHand),debit);moneyOnHand-=fromCash;bank=Math.max(0,bank-(debit-fromCash));}else moneyOnHand+=cashDelta;const tx={label:`Investment · ${transaction.label}`,amount:cashDelta,year:g.year};return {...g,money:moneyOnHand,bankBalance:bank,investments:{...next,transactions:[transaction,...(next.transactions||[])].slice(0,400)},investmentHistory:[transaction,...(g.investmentHistory||[])].slice(0,400),transactions:[tx,...(g.transactions||[])],lifetimeIncome:(g.lifetimeIncome||0)+(direction==='sell'?Math.max(0,realized):0),lifetimeSpending:(g.lifetimeSpending||0)+(direction==='buy'?fee:fee+Math.max(0,-realized))};});
    if(direction==='buy')setNotice(`Order filled at ${price(current.price)} per share/token plus a $2 simulated trading fee.`);else setNotice('');
  };
  const toggleSection=value=>{setSection(value);setNotice('');};
  const confirmBuy=()=>{if(!buyConfirmation)return;const asset=universe.find(item=>item.id===buyConfirmation.assetId);if(!asset){setBuyConfirmation(null);setNotice('This listing is no longer available.');return;}trade(asset,'buy',true,buyConfirmation.amount);setBuyConfirmation(null);};
  const buyAsset=buyConfirmation?universe.find(item=>item.id===buyConfirmation.assetId):null;
  const buyFee=2;const buyTotal=(buyConfirmation?.amount||0)+buyFee;const buyUnits=buyAsset?.price?((buyConfirmation?.amount||0)/buyAsset.price):0;const availableBalance=(game.money||0)+(game.bankBalance||0);
  return <div className="investment-screen-content">
    {buyConfirmation&&buyAsset&&<div className="investment-sale-backdrop" onClick={()=>setBuyConfirmation(null)}><section className="investment-sale-dialog investment-buy-dialog" role="dialog" aria-modal="true" aria-labelledby="investment-buy-title" onClick={event=>event.stopPropagation()}><button className="investment-sale-close" onClick={()=>setBuyConfirmation(null)} aria-label="Cancel purchase"><X size={19}/></button><span className="investment-sale-icon"><ArrowUpRight size={25}/></span><small>REVIEW ORDER</small><h3 id="investment-buy-title">Confirm investment</h3><p>{buyAsset.name} · {buyAsset.symbol} · {buyAsset.assetClass} / {buyAsset.category}</p><div className="investment-sale-details"><span>Simulated quote<b>{price(buyAsset.price)} per unit</b></span><span>Order amount<b>{money(buyConfirmation.amount)}</b></span><span>Estimated units<b>{buyUnits.toLocaleString(undefined,{maximumFractionDigits:6})}</b></span><span>Trading fee<b>{money(buyFee)}</b></span><span className="sale-net-row">Total debit<b>{money(buyTotal)}</b></span><span>Available before<b>{money(availableBalance)}</b></span><span className="sale-pnl-row">Available after<b>{money(availableBalance-buyTotal)}</b></span></div>{buyAsset.assetClass==='Memecoin'&&<p className="buy-risk-warning">Very high risk: this memecoin can swing sharply or be rugged, which may reduce its value to zero. Units are estimates and the simulated quote may change.</p>}<div className="investment-buy-confirm-actions"><button className="investment-buy-cancel" onClick={()=>setBuyConfirmation(null)}>Review later</button><button className="investment-sale-done" disabled={buyTotal>availableBalance} onClick={confirmBuy}>{buyTotal>availableBalance?'Insufficient funds':`Confirm · ${money(buyTotal)}`}</button></div></section></div>}
    {saleReceipt&&<div className="investment-sale-backdrop" onClick={()=>setSaleReceipt(null)}><section className="investment-sale-dialog" role="dialog" aria-modal="true" aria-labelledby="investment-sale-title" onClick={event=>event.stopPropagation()}><button className="investment-sale-close" onClick={()=>setSaleReceipt(null)} aria-label="Close sale details"><X size={19}/></button><span className="investment-sale-icon"><Check size={25}/></span><small>TRADE COMPLETE</small><h3 id="investment-sale-title">{saleReceipt.rugged?'Position written off':'Position sold'}</h3><p>{saleReceipt.name} · {saleReceipt.symbol}</p><div className="investment-sale-details"><span>Units sold<b>{saleReceipt.units.toLocaleString(undefined,{maximumFractionDigits:6})}</b></span><span>Execution price<b>{price(saleReceipt.price)}</b></span><span>Gross proceeds<b>{money(saleReceipt.gross)}</b></span><span>Trading fee<b>{money(saleReceipt.fee)}</b></span><span className="sale-net-row">Net proceeds<b>{money(saleReceipt.proceeds)}</b></span><span className="sale-pnl-row">Realized P&amp;L<b className={saleReceipt.realized>=0?'pnl-positive':'pnl-negative'}>{saleReceipt.realized>=0?'+':''}{money(saleReceipt.realized)}</b></span></div><button className="investment-sale-done" onClick={()=>setSaleReceipt(null)}>Done</button></section></div>}
    <header className="investment-screen-heading"><div><span className="investment-kicker">MARKET SIMULATOR</span><h3>Investments</h3><p>Prices and news are fictional, simulated game data.</p></div><span className="market-live-pill"><i/>MARKET LIVE</span></header>
    <div className="investment-switcher">{['Market','Portfolio','History'].map(item=><button key={item} className={section===item?'selected':''} onClick={()=>toggleSection(item)}>{item==='Market'?<ChartNoAxesCombined size={16}/>:item==='Portfolio'?<Wallet size={16}/>:<Clock3 size={16}/>} {item}</button>)}</div>
    {section==='Market'&&<>
      <div className="portfolio-overview"><div><small>INVESTED VALUE</small><b>{money(summary.value)}</b><span className={summary.total>=0?'pnl-positive':'pnl-negative'}>Total P&L {summary.total>=0?'+':''}{money(summary.total)}</span></div><Sparkline values={market.portfolioHistory?.length?market.portfolioHistory:[0,0,0,0]}/></div>
      <div className="market-headline"><Newspaper size={17}/><span><b>Market news</b><small>{market.news?.[0]?.headline||'Markets are open. Prices are updating in real time.'}</small></span></div>
      <div className="market-class-tabs">{classes.map(item=><button key={item} className={assetClass===item?'selected':''} onClick={()=>{setAssetClass(item);setCategory('All');setSelectedId('');}}>{item==='Stocks'?'📈':item==='Bonds'?'🧾':item==='Crypto'?'₿':'🐸'} {item}</button>)}</div>
      <div className="market-filter-row">{categories.map(item=><button className={category===item?'active':''} key={item} onClick={()=>setCategory(item)}>{item}</button>)}</div>
      <div className="market-instrument-list">{filtered.map(asset=><button className={`market-instrument ${selected?.id===asset.id?'chosen':''}`} key={asset.id} onClick={()=>setSelectedId(asset.id)}><span className={`instrument-emblem ${asset.assetClass==='Memecoin'?'meme':asset.assetClass.toLowerCase()}`}>{asset.assetClass==='Stock'?'↗':asset.assetClass==='Bond'?'▤':asset.assetClass==='Crypto'?'◈':'🐸'}</span><span className="instrument-summary"><b>{asset.name}</b><small>{asset.symbol} · {asset.category}</small></span><span className="instrument-chart-mini"><Sparkline values={asset.history}/></span><span className="instrument-quote"><b>{price(asset.price)}</b><small className={(asset.changePct||0)>=0?'pnl-positive':'pnl-negative'}>{(asset.changePct||0)>=0?'+':''}{(asset.changePct||0).toFixed(2)}%</small></span></button>)}</div>
      {selected&&<article className="instrument-detail-card"><div className="instrument-detail-top"><div><small>{selected.assetClass.toUpperCase()} · {selected.category.toUpperCase()}</small><h4>{selected.name}</h4><span>{selected.symbol} · Simulated quote updates while this page is open</span></div><b>{price(selected.price)}</b></div><Sparkline values={selected.history} large/><div className="instrument-facts"><span>Change <b className={(selected.changePct||0)>=0?'pnl-positive':'pnl-negative'}>{(selected.changePct||0)>=0?'+':''}{(selected.changePct||0).toFixed(2)}%</b></span><span>{selected.assetClass==='Bond'?'Annual coupon':'Annual yield'} <b>{(selected.annualYield*100).toFixed(2)}%</b></span><span>{selected.assetClass==='Bond'?'Credit / maturity':selected.assetClass==='Stock'?'P/E ratio':'Investment style'} <b>{selected.assetClass==='Bond'?`${selected.creditRating||'A'} · ${selected.maturityYears||'—'} yr`:selected.assetClass==='Stock'?`${selected.priceEarnings||'—'}×`:selected.assetClass==='Memecoin'?'Extreme risk':selected.assetClass==='Crypto'?'High risk':'Market risk'}</b></span></div>{selected.assetClass==='Memecoin'&&<p className="meme-risk-note">Memecoins can rise sharply, lose nearly all value, or be rugged. A rug pull removes the coin from active trading.</p>}<div className="investment-order-row"><label>Order amount<input type="number" min="10" step="50" value={orderAmount} onChange={event=>setOrderAmount(event.target.value)}/></label><button className="investment-buy" onClick={()=>trade(selected,'buy')}><ArrowUpRight size={16}/> Buy</button>{holdings.some(position=>position.assetId===selected.id)&&<button className="investment-sell" onClick={()=>trade(selected,'sell')}><ArrowDownRight size={16}/> Sell all</button>}</div></article>}
      {notice&&<div className="investment-notice">{notice}</div>}
    </>}
    {section==='Portfolio'&&<>
      <div className="portfolio-overview portfolio-total"><div><small>TOTAL PORTFOLIO VALUE</small><b>{money(summary.value)}</b><span className={summary.total>=0?'pnl-positive':'pnl-negative'}>{summary.total>=0?'+':''}{money(summary.total)} all-time P&L</span></div><Sparkline values={market.portfolioHistory?.length?market.portfolioHistory:[0,0,0,0]} large/></div>
      <div className="portfolio-metrics"><div><small>Cost basis</small><b>{money(summary.invested)}</b></div><div><small>Unrealized P&L</small><b className={summary.unrealized>=0?'pnl-positive':'pnl-negative'}>{summary.unrealized>=0?'+':''}{money(summary.unrealized)}</b></div><div><small>Realized P&L</small><b className={summary.realized>=0?'pnl-positive':'pnl-negative'}>{summary.realized>=0?'+':''}{money(summary.realized)}</b></div></div>
      <div className="investment-section-title"><b>Your positions</b><span>{summary.positions.length} holdings</span></div>{summary.positions.length?summary.positions.map(position=><article className="portfolio-position" key={position.assetId}><div className="position-main"><span className="position-type-icon">{position.asset?.assetClass==='Bond'?'🧾':position.asset?.assetClass==='Crypto'?'◈':position.asset?.assetClass==='Memecoin'?'🐸':'📈'}</span><div><b>{position.asset?.name||position.symbol}</b><small>{position.units.toLocaleString(undefined,{maximumFractionDigits:6})} units · Cost basis {money(position.costBasis)}</small></div><div className="position-values"><b>{money(position.value)}</b><small className={position.unrealized>=0?'pnl-positive':'pnl-negative'}>{position.unrealized>=0?'+':''}{money(position.unrealized)}</small></div></div><Sparkline values={position.asset?.history||[0,0]}/><button className="position-sell-button" disabled={!position.asset} onClick={()=>position.asset&&trade(position.asset,'sell')}>{position.asset?.rugged?'Remove worthless position':position.asset?'Sell position':'Market unavailable'}</button></article>):<div className="investment-empty"><span>🪴</span><b>Your portfolio is waiting to grow</b><small>Browse the market and buy your first share, bond, or token.</small><button onClick={()=>setSection('Market')}>Explore investments</button></div>}
      <div className="market-news-feed"><h4><Newspaper size={16}/> Recent market news</h4>{(market.news||[]).slice(0,8).map(item=><div className={`market-news-item ${item.type||''}`} key={item.id}><span>{item.type==='rugpull'?'⚠️':item.type==='spike'?'🚀':item.type==='DIVIDEND'?'💵':item.type==='MATURITY'?'🏁':item.type==='listing'?'🪙':'📰'}</span><div><b>{item.headline}</b><small>Age {recordAge(item,game)}</small></div></div>)}</div>
    </>}
    {section==='History'&&<>
      <div className="history-summary-card"><Coins size={21}/><div><b>Investment activity</b><small>Orders, realized gains and losses, distributions, and market events.</small></div></div>
      {(market.transactions||[]).length?(market.transactions||[]).slice(0,70).map(item=><div className={`investment-history-row ${item.type||''}`} key={item.id}><span>{item.type==='BUY'?'↗':item.type==='SELL'?'↘':item.type==='WRITE_OFF'?'⚠️':item.type==='rugpull'?'⚠️':item.type==='spike'?'🚀':item.type==='DIVIDEND'?'💵':item.type==='MATURITY'?'🏁':item.type==='listing'?'🪙':'📰'}</span><div><b>{item.label}</b><small>Age {recordAge(item,game)}{item.units?` · ${item.units.toLocaleString(undefined,{maximumFractionDigits:6})} units at ${price(item.price)}`:''}{item.realizedPnl!=null?` · Realized P&L ${item.realizedPnl>=0?'+':''}${money(item.realizedPnl)}`:''}</small></div>{item.amount!=null&&<strong className={item.amount>=0?'pnl-positive':'pnl-negative'}>{item.amount>=0?'+':''}{money(item.amount)}</strong>}</div>):<div className="investment-empty"><span>📒</span><b>No investment activity yet</b><small>Your completed buy and sell orders will appear here.</small></div>}
    </>}
    <footer className="investment-disclaimer"><RefreshCw size={13}/> Simulated game prices only. No real investments or money are involved.</footer>
  </div>;
}
